apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rabbitmq
  namespace: deploy
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend-rabbitmq
  template:
    metadata:
      name: rabbitmq-pod
      labels:
        app: backend-rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.8-alpine
        imagePullPolicy: Always
        name: rabbitmq
        ports:
        - containerPort: 5672
          protocol: TCP
      restartPolicy: Always