apiVersion: batch/v1
kind: Job
metadata:
  name: job-migrations
  namespace: deploy
spec:
  template:
    metadata:
      name: migrations-pod
      labels:
        app: migrations-backend
    spec:
      containers:
      - image: twelvecloud/coursework5:backend
        imagePullPolicy: Always
        command: ["./migrations-entrypoint.sh"]
        name: migrations
        ports:
        - containerPort: 8000
          protocol: TCP
        envFrom:
        - secretRef:
            name: secret-backend
        - prefix: CONFIG_
          configMapRef:
            name: configmap-backend
      restartPolicy: OnFailure