apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-database-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /k8s/stocktrader/postgres/database1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-database-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /k8s/stocktrader/postgres/database2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-database-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /k8s/stocktrader/postgres/database3