apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-deploy
  namespace: deploy
spec:
  hard:
    requests.cpu: 5
    requests.memory: 7Gi
    limits.cpu: 7
    limits.memory: 10Gi
    pods: 20
    replicationcontrollers: 10
    secrets: 10
    configmaps: 10
    services: 20
    services.loadbalancers: 5
    services.nodeports: 5
    resourcequotas: 1
    persistentvolumeclaims: 6