apiVersion: v1
kind: Service
metadata:
  name: service-backend
  namespace: deploy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30007
  selector:
    app: backend-django