apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-database
  namespace: deploy
spec:
  serviceName: service-database-headless
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: database-postgres
  template:
    metadata:
      name: pod-database
      labels:
        app: database-postgres
    spec:
      containers:
      - image: postgres:14.4-alpine
        imagePullPolicy: Always
        name: database
        ports:
        - containerPort: 5432
          protocol: TCP
        envFrom:
        - secretRef:
            name: secret-backend
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 1Mi
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ""