# Generated by Django 4.1.3 on 2022-12-01 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Balance')),
                ('balance_with_shares', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Shares balance')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'Account',
                'ordering': ('balance', 'balance_with_shares'),
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'db_table': 'Broker',
                'ordering': ('name', 'rate'),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(None, 'Choose type'), ('buy', 'Buy'), ('sel', 'Sell')], max_length=3, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('company', models.CharField(max_length=256, verbose_name='Company')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shares.broker', verbose_name='Broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'Order',
                'ordering': ('type', 'company', 'amount'),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('balance', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Balance')),
                ('balance_with_shares', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Shares balance')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shares.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'AccountHistory',
                'verbose_name_plural': 'AccountHistories',
                'db_table': 'AccountHistory',
                'ordering': ('balance', 'balance_with_shares'),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='shares.broker', verbose_name='Broker'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256, verbose_name='Company')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('current_price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Current price')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='shares.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'Stock',
                'ordering': ('company', 'amount', 'current_price'),
                'unique_together': {('company', 'account')},
            },
        ),
    ]
